export declare const bigBlob: string
export declare const button: string
export declare const content: string
export declare const downloadButtons: string
export declare const mainScreen: string
export declare const metaBadge: string
export declare const officialMeta: string
export declare const phone: string
export declare const presentation: string
export declare const presentationDesktop: string
export declare const secondScreen: string
export declare const smallBlob: string
